fullnameOverride: "dhedalos-app-frontend-hub"

replicaCount: 1
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-native
    nginx.ingress.kubernetes.io/affinity: cookie
  hosts:
    - essencia.dhedalos.com
  tls:
    - secretName: dhedalos-app-frontend-hub
      hosts:
        - essencia.dhedalos.com