apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dhedalos-app-frontend-nextjs.fullname" . }}-envs
  labels:
    {{- include "dhedalos-app-frontend-nextjs.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
type: Opaque
stringData:
    SCHEDULE_APP_KEY: 'scheduleAppKey'
    {{- if .Values.ingress.enabled }}
    NEXTAUTH_URL: 'https://{{ .Values.ingress.hostname }}'
    {{- else }}
    NEXTAUTH_URL: '{{ include "dhedalos-app-frontend-nextjs.fullname" . }}'
    {{- end }}
    NEXTAUTH_SECRET: 'nextAuthSecret'
    SCHEDULE_URL: 'http://dhedalos-app-laravel-schedule-manager'
    API_URL: 'http://dhedalos-app-backend-wp'
    NEXT_DHEDALOS_PRIVACY_POLICY: 'https://privacidade.sebraeingresse.com.br'
    NEXT_DATADOG_ENV: 'production-oci'
    NEXT_DATADOG_SERVICE: 'dhedalos-hub'
    NEXT_DATADOG_CLIENT_ID: 'abc123'
    NEXT_DATADOG_CLIENT_TOKEN: 'abc123'
    NOVU_API_URL: 'https://api.novu.co/v1/events/trigger'
    NOVU_API_KEY: 'novuApiKey'